export const mockBookings = [
  {
    id: "b1a2c3d4-0001",
    camera_id: "g7x-mark-iii",
    duration_type: "1-2day",
    start_date: "2026-07-12",
    end_date: "2026-07-13",
    total_price: 1000,
    full_name: "Jane M. Doe",
    date_of_birth: "2001-01-01",
    age: 25,
    contact_no: "09876543210",
    email: "janedoe@gmail.com",
    fulfillment_type: "delivery",
    delivery_address: "Aling Susan Store, Mandaue City",
    will_pickup_mandaue: null,
    preferred_time: "15:00",
    return_time: "09:00",
    returning_method: "personal_casuntingan",
    facebook_url: "facebook.com/jane.doe",
    instagram_url: "instagram.com/jane.doe",
    tiktok_url: null,
    renting_purpose: "birthday",
    renting_purpose_other: null,
    allow_social_share: true,
    id_photo_url: "/equipment-mock/sample-id.png",
    selfie_with_id_url: "/equipment-mock/sample-selfie.png",
    signature_url: "/equipment-mock/sample-signature.png",
    terms_agreed: true,
    terms_agreed_at: "2026-07-10T14:08:00Z",
    downpayment_status: "pending",
    status: "pending",
    created_at: "2026-07-10T14:08:00Z",
    delete_after: "2026-07-27",
  },
  {
    id: "b1a2c3d4-0002",
    camera_id: "g7x-mark-iii",
    duration_type: "1-2day",
    start_date: "2026-07-17",
    end_date: "2026-07-18",
    total_price: 1000,
    full_name: "Mari Juana",
    date_of_birth: "1998-05-20",
    age: 28,
    contact_no: "09123456789",
    email: "mari.juana@gmail.com",
    fulfillment_type: "pickup",
    delivery_address: null,
    will_pickup_mandaue: true,
    preferred_time: "13:00",
    return_time: "13:00",
    returning_method: "maxim_angkas",
    facebook_url: "facebook.com/mari.juana",
    instagram_url: null,
    tiktok_url: "tiktok.com/@mari.juana",
    renting_purpose: "travel",
    renting_purpose_other: null,
    allow_social_share: false,
    id_photo_url: "/equipment-mock/sample-id.png",
    selfie_with_id_url: "/equipment-mock/sample-selfie.png",
    signature_url: "/equipment-mock/sample-signature.png",
    terms_agreed: true,
    terms_agreed_at: "2026-07-10T16:32:00Z",
    downpayment_status: "received",
    status: "pending",
    created_at: "2026-07-10T16:32:00Z",
    delete_after: "2026-08-01",
  },
];

// helper — mirrors what a real Supabase query for a single booking would return
export function getMockBookingById(id) {
  return mockBookings.find((booking) => booking.id === id) ?? null;
}
